apiVersion: v1
kind: ConfigMap
metadata:
  name: spinnaker-demo-config
  namespace: default
data:
  new_feature: "true"

---

apiVersion: apps/v1
kind: Deployment
metadata:
  name: spinnaker-demo-v1
  namespace: default
  labels:
    source: demo
    stack: frontend
    app: spinnaker
spec:
  replicas: 3
  selector:
    matchLabels:
      source: demo-prod
      app: spinnaker
  template:
    metadata:
      labels:
        source: demo-prod
        app: spinnaker
    spec:
      containers:
      - name: primary
        image: index.docker.io/konikris/spinnaker-app:v5
        ports:
        - containerPort: 8000
        readinessProbe:
          httpGet:
            path: /
            port: 8000
        envFrom:
        - configMapRef:
            name: spinnaker-demo-config
